quarkus:
  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      url: jdbc:h2:mem:quarkus-social
      max-size: 16

  h2:
    console:
      enabled: true
      path: /h2-console